#!/usr/bin/env bash

for x in "1:1" "3:1" "5:1" "7:1" "1:2"; do
  right="${x:0:1}"
  down="${x:2:1}"
  awk -v right=${right} -v down=${down} -f ./count-collisions.awk ./input.txt
done |
  awk 'BEGIN {product=1} $1 == "Hit" {product *= $2} END {print product}'

